export default function () {
  return {
    productJSON : [],
    csvCols : [
      // "Brand","Manufacturer_ID","Product_Code",	"Product_Name","Supplier_SKU_ID","Manufacturer_SKU_ID","MSRP","MAP","Cost_Price","Weight","Stock","SKU_Available_Date","Category1_Unique",
      // "Category1_Name","Category2_Unique","Category2_Name","Category3_Unique","Category3_Name","Category4_Unique","Category4_Name","Category5_Unique","Category5_Name","Category6_Unique",
      // "Category6_Name","Product_Description","SKU_Description","Large_Image_Path","Thumbnail_Image_Path","Supplier_Code","Swatch_Image_Path","Color_Name","Size_Code","Size_Name",
      // "Fit_Code","Fit_Name"
    ],
    mapData:{},
    productData:[
      // {
      //   "Brand": "TM",
      //   "Manufacturer_ID": 14,
      //   "Product_Code": 14,
      //   "Product_Name": "Sentinel&#45;Mens Cottonpoly 6040 Knit Polo Shirt W Mic Loops Pen Pocket",
      //   "Supplier_SKU_ID": "014.BL.M",
      //   "Manufacturer_SKU_ID": "014.BL.M",
      //   "MSRP": 35,
      //   "MAP": 35,
      //   "Cost_Price": 35,
      //   "Weight": 1,
      //   "Stock": 1000,
      //   "SKU_Available_Date": "",
      //   "Category1_Unique": "TM>TM_Knits>TM_Knits_BlendedPolyester",
      //   "Category1_Name": "Tri-Mountain>Knits>BlendedPolyester",
      //   "Category2_Unique": "TM>TM_Workwear>TM_Workwear_Knits",
      //   "Category2_Name": "Tri-Mountain>Workwear>Knits",
      //   "Category3_Unique": "TM>TM_Knits>TM_Knits_TMUltracool",
      //   "Category3_Name": "Tri-Mountain>Knits>Tri-Mountain Ultracool",
      //   "Category4_Unique": "TM>TM_Knits>TM_Knits_TMUltracool",
      //   "Category4_Name": "Tri-Mountain>Knits>Tri-Mountain Ultracool",
      //   "Category5_Unique": "ALL_HO>ALL_HO_Shirts",
      //   "Category5_Name": "Hospitality>Shirts",
      //   "Category6_Unique": "ALL_HO>ALL_HO_Shirts>ALL_HO_Shirts_Mens",
      //   "Category6_Name": "Hospitality>Shirts>Mens",
      //   "Product_Description": "<strong>Features:</strong><ul><li>Sentinel&&#35;45;Mens Cottonpoly 6040 Knit Polo Shirt W Mic Loops Pen Pocket</li></ul><a href='https://sellerscommerce.azureedge.net/images/147/size_chart_2013.pdf'target='_blank'>Click Here For Size Chart </a></li></ul></br>",
      //   "SKU_Description": "",
      //   "Large_Image_Path": "147/l/014_sentinel_bl.jpg",
      //   "Thumbnail_Image_Path": "147/s/014_sentinel_bl.jpg",
      //   "Supplier_Code": "",
      //   "Swatch_Image_Path": "147/sw/tm_black-bl_sw.jpg",
      //   "Color_Code": "Black-BL",
      //   "Color_Name": "Black (BL)",
      //   "Size_Code": "M",
      //   "Size_Name": "M",
      //   "Fit_Code": "Regular",
      //   "Fit_Name": "Regular"
      // },
      // {
      //   "Brand": "TM",
      //   "Manufacturer_ID": 14,
      //   "Product_Code": 14,
      //   "Product_Name": "Sentinel&#45;Mens Cottonpoly 6040 Knit Polo Shirt W Mic Loops Pen Pocket",
      //   "Supplier_SKU_ID": "014.BL.L",
      //   "Manufacturer_SKU_ID": "014.BL.L",
      //   "MSRP": 35,
      //   "MAP": 35,
      //   "Cost_Price": 35,
      //   "Weight": 1,
      //   "Stock": 1000,
      //   "SKU_Available_Date": "",
      //   "Category1_Unique": "TM>TM_Knits>TM_Knits_BlendedPolyester",
      //   "Category1_Name": "Tri-Mountain>Knits>BlendedPolyester",
      //   "Category2_Unique": "TM>TM_Workwear>TM_Workwear_Knits",
      //   "Category2_Name": "Tri-Mountain>Workwear>Knits",
      //   "Category3_Unique": "TM>TM_Knits>TM_Knits_TMUltracool",
      //   "Category3_Name": "Tri-Mountain>Knits>Tri-Mountain Ultracool",
      //   "Category4_Unique": "TM>TM_Knits>TM_Knits_TMUltracool",
      //   "Category4_Name": "Tri-Mountain>Knits>Tri-Mountain Ultracool",
      //   "Category5_Unique": "ALL_HO>ALL_HO_Shirts",
      //   "Category5_Name": "Hospitality>Shirts",
      //   "Category6_Unique": "ALL_HO>ALL_HO_Shirts>ALL_HO_Shirts_Mens",
      //   "Category6_Name": "Hospitality>Shirts>Mens",
      //   "Product_Description": "<strong>Features:</strong><ul><li>Sentinel&&#35;45;Mens Cottonpoly 6040 Knit Polo Shirt W Mic Loops Pen Pocket</li></ul><a href='https://sellerscommerce.azureedge.net/images/147/size_chart_2013.pdf'target='_blank'>Click Here For Size Chart </a></li></ul></br>",
      //   "SKU_Description": "",
      //   "Large_Image_Path": "147/l/014_sentinel_bl.jpg",
      //   "Thumbnail_Image_Path": "147/s/014_sentinel_bl.jpg",
      //   "Supplier_Code": "",
      //   "Swatch_Image_Path": "147/sw/tm_black-bl_sw.jpg",
      //   "Color_Code": "Black-BL",
      //   "Color_Name": "Black (BL)",
      //   "Size_Code": "L",
      //   "Size_Name": "L",
      //   "Fit_Code": "Regular",
      //   "Fit_Name": "Regular"
      // },
      // {
      //   "Brand": "TM",
      //   "Manufacturer_ID": 14,
      //   "Product_Code": 14,
      //   "Product_Name": "Sentinel&#45;Mens Cottonpoly 6040 Knit Polo Shirt W Mic Loops Pen Pocket",
      //   "Supplier_SKU_ID": "014.BL.XL",
      //   "Manufacturer_SKU_ID": "014.BL.XL",
      //   "MSRP": 35,
      //   "MAP": 35,
      //   "Cost_Price": 35,
      //   "Weight": 1,
      //   "Stock": 1000,
      //   "SKU_Available_Date": "",
      //   "Category1_Unique": "TM>TM_Knits>TM_Knits_BlendedPolyester",
      //   "Category1_Name": "Tri-Mountain>Knits>BlendedPolyester",
      //   "Category2_Unique": "TM>TM_Workwear>TM_Workwear_Knits",
      //   "Category2_Name": "Tri-Mountain>Workwear>Knits",
      //   "Category3_Unique": "TM>TM_Knits>TM_Knits_TMUltracool",
      //   "Category3_Name": "Tri-Mountain>Knits>Tri-Mountain Ultracool",
      //   "Category4_Unique": "TM>TM_Knits>TM_Knits_TMUltracool",
      //   "Category4_Name": "Tri-Mountain>Knits>Tri-Mountain Ultracool",
      //   "Category5_Unique": "ALL_HO>ALL_HO_Shirts",
      //   "Category5_Name": "Hospitality>Shirts",
      //   "Category6_Unique": "ALL_HO>ALL_HO_Shirts>ALL_HO_Shirts_Mens",
      //   "Category6_Name": "Hospitality>Shirts>Mens",
      //   "Product_Description": "<strong>Features:</strong><ul><li>Sentinel&&#35;45;Mens Cottonpoly 6040 Knit Polo Shirt W Mic Loops Pen Pocket</li></ul><a href='https://sellerscommerce.azureedge.net/images/147/size_chart_2013.pdf'target='_blank'>Click Here For Size Chart </a></li></ul></br>",
      //   "SKU_Description": "",
      //   "Large_Image_Path": "147/l/014_sentinel_bl.jpg",
      //   "Thumbnail_Image_Path": "147/s/014_sentinel_bl.jpg",
      //   "Supplier_Code": "",
      //   "Swatch_Image_Path": "147/sw/tm_black-bl_sw.jpg",
      //   "Color_Code": "Black-BL",
      //   "Color_Name": "Black (BL)",
      //   "Size_Code": "XL",
      //   "Size_Name": "XL",
      //   "Fit_Code": "Regular",
      //   "Fit_Name": "Regular"
      // },
      // {
      //   "Brand": "TM",
      //   "Manufacturer_ID": 14,
      //   "Product_Code": 14,
      //   "Product_Name": "Sentinel&#45;Mens Cottonpoly 6040 Knit Polo Shirt W Mic Loops Pen Pocket",
      //   "Supplier_SKU_ID": "014.BL.2XL",
      //   "Manufacturer_SKU_ID": "014.BL.2XL",
      //   "MSRP": 37,
      //   "MAP": 37,
      //   "Cost_Price": 37,
      //   "Weight": 1,
      //   "Stock": 1000,
      //   "SKU_Available_Date": "",
      //   "Category1_Unique": "TM>TM_Knits>TM_Knits_BlendedPolyester",
      //   "Category1_Name": "Tri-Mountain>Knits>BlendedPolyester",
      //   "Category2_Unique": "TM>TM_Workwear>TM_Workwear_Knits",
      //   "Category2_Name": "Tri-Mountain>Workwear>Knits",
      //   "Category3_Unique": "TM>TM_Knits>TM_Knits_TMUltracool",
      //   "Category3_Name": "Tri-Mountain>Knits>Tri-Mountain Ultracool",
      //   "Category4_Unique": "TM>TM_Knits>TM_Knits_TMUltracool",
      //   "Category4_Name": "Tri-Mountain>Knits>Tri-Mountain Ultracool",
      //   "Category5_Unique": "ALL_HO>ALL_HO_Shirts",
      //   "Category5_Name": "Hospitality>Shirts",
      //   "Category6_Unique": "ALL_HO>ALL_HO_Shirts>ALL_HO_Shirts_Mens",
      //   "Category6_Name": "Hospitality>Shirts>Mens",
      //   "Product_Description": "<strong>Features:</strong><ul><li>Sentinel&&#35;45;Mens Cottonpoly 6040 Knit Polo Shirt W Mic Loops Pen Pocket</li></ul><a href='https://sellerscommerce.azureedge.net/images/147/size_chart_2013.pdf'target='_blank'>Click Here For Size Chart </a></li></ul></br>",
      //   "SKU_Description": "",
      //   "Large_Image_Path": "147/l/014_sentinel_bl.jpg",
      //   "Thumbnail_Image_Path": "147/s/014_sentinel_bl.jpg",
      //   "Supplier_Code": "",
      //   "Swatch_Image_Path": "147/sw/tm_black-bl_sw.jpg",
      //   "Color_Code": "Black-BL",
      //   "Color_Name": "Black (BL)",
      //   "Size_Code": "2XL",
      //   "Size_Name": "2XL",
      //   "Fit_Code": "Regular",
      //   "Fit_Name": "Regular"
      // },
      // {
      //   "Brand": "TM",
      //   "Manufacturer_ID": 14,
      //   "Product_Code": 14,
      //   "Product_Name": "Sentinel&#45;Mens Cottonpoly 6040 Knit Polo Shirt W Mic Loops Pen Pocket",
      //   "Supplier_SKU_ID": "014.BL.3XL",
      //   "Manufacturer_SKU_ID": "014.BL.3XL",
      //   "MSRP": 39,
      //   "MAP": 39,
      //   "Cost_Price": 39,
      //   "Weight": 1,
      //   "Stock": 1000,
      //   "SKU_Available_Date": "",
      //   "Category1_Unique": "TM>TM_Knits>TM_Knits_BlendedPolyester",
      //   "Category1_Name": "Tri-Mountain>Knits>BlendedPolyester",
      //   "Category2_Unique": "TM>TM_Workwear>TM_Workwear_Knits",
      //   "Category2_Name": "Tri-Mountain>Workwear>Knits",
      //   "Category3_Unique": "TM>TM_Knits>TM_Knits_TMUltracool",
      //   "Category3_Name": "Tri-Mountain>Knits>Tri-Mountain Ultracool",
      //   "Category4_Unique": "TM>TM_Knits>TM_Knits_TMUltracool",
      //   "Category4_Name": "Tri-Mountain>Knits>Tri-Mountain Ultracool",
      //   "Category5_Unique": "ALL_HO>ALL_HO_Shirts",
      //   "Category5_Name": "Hospitality>Shirts",
      //   "Category6_Unique": "ALL_HO>ALL_HO_Shirts>ALL_HO_Shirts_Mens",
      //   "Category6_Name": "Hospitality>Shirts>Mens",
      //   "Product_Description": "<strong>Features:</strong><ul><li>Sentinel&&#35;45;Mens Cottonpoly 6040 Knit Polo Shirt W Mic Loops Pen Pocket</li></ul><a href='https://sellerscommerce.azureedge.net/images/147/size_chart_2013.pdf'target='_blank'>Click Here For Size Chart </a></li></ul></br>",
      //   "SKU_Description": "",
      //   "Large_Image_Path": "147/l/014_sentinel_bl.jpg",
      //   "Thumbnail_Image_Path": "147/s/014_sentinel_bl.jpg",
      //   "Supplier_Code": "",
      //   "Swatch_Image_Path": "147/sw/tm_black-bl_sw.jpg",
      //   "Color_Code": "Black-BL",
      //   "Color_Name": "Black (BL)",
      //   "Size_Code": "3XL",
      //   "Size_Name": "3XL",
      //   "Fit_Code": "Regular",
      //   "Fit_Name": "Regular"
      // },
      // {
      //   "Brand": "TM",
      //   "Manufacturer_ID": 14,
      //   "Product_Code": 14,
      //   "Product_Name": "Sentinel&#45;Mens Cottonpoly 6040 Knit Polo Shirt W Mic Loops Pen Pocket",
      //   "Supplier_SKU_ID": "014.BL.4XL",
      //   "Manufacturer_SKU_ID": "014.BL.4XL",
      //   "MSRP": 41,
      //   "MAP": 41,
      //   "Cost_Price": 41,
      //   "Weight": 1,
      //   "Stock": 1000,
      //   "SKU_Available_Date": "",
      //   "Category1_Unique": "TM>TM_Knits>TM_Knits_BlendedPolyester",
      //   "Category1_Name": "Tri-Mountain>Knits>BlendedPolyester",
      //   "Category2_Unique": "TM>TM_Workwear>TM_Workwear_Knits",
      //   "Category2_Name": "Tri-Mountain>Workwear>Knits",
      //   "Category3_Unique": "TM>TM_Knits>TM_Knits_TMUltracool",
      //   "Category3_Name": "Tri-Mountain>Knits>Tri-Mountain Ultracool",
      //   "Category4_Unique": "TM>TM_Knits>TM_Knits_TMUltracool",
      //   "Category4_Name": "Tri-Mountain>Knits>Tri-Mountain Ultracool",
      //   "Category5_Unique": "ALL_HO>ALL_HO_Shirts",
      //   "Category5_Name": "Hospitality>Shirts",
      //   "Category6_Unique": "ALL_HO>ALL_HO_Shirts>ALL_HO_Shirts_Mens",
      //   "Category6_Name": "Hospitality>Shirts>Mens",
      //   "Product_Description": "<strong>Features:</strong><ul><li>Sentinel&&#35;45;Mens Cottonpoly 6040 Knit Polo Shirt W Mic Loops Pen Pocket</li></ul><a href='https://sellerscommerce.azureedge.net/images/147/size_chart_2013.pdf'target='_blank'>Click Here For Size Chart </a></li></ul></br>",
      //   "SKU_Description": "",
      //   "Large_Image_Path": "147/l/014_sentinel_bl.jpg",
      //   "Thumbnail_Image_Path": "147/s/014_sentinel_bl.jpg",
      //   "Supplier_Code": "",
      //   "Swatch_Image_Path": "147/sw/tm_black-bl_sw.jpg",
      //   "Color_Code": "Black-BL",
      //   "Color_Name": "Black (BL)",
      //   "Size_Code": "4XL",
      //   "Size_Name": "4XL",
      //   "Fit_Code": "Regular",
      //   "Fit_Name": "Regular"
      // },
      // {
      //   "Brand": "TM",
      //   "Manufacturer_ID": 14,
      //   "Product_Code": 14,
      //   "Product_Name": "Sentinel&#45;Mens Cottonpoly 6040 Knit Polo Shirt W Mic Loops Pen Pocket",
      //   "Supplier_SKU_ID": "014.BL.LT",
      //   "Manufacturer_SKU_ID": "014.BL.LT",
      //   "MSRP": 37,
      //   "MAP": 37,
      //   "Cost_Price": 37,
      //   "Weight": 1,
      //   "Stock": 1000,
      //   "SKU_Available_Date": "",
      //   "Category1_Unique": "TM>TM_Knits>TM_Knits_BlendedPolyester",
      //   "Category1_Name": "Tri-Mountain>Knits>BlendedPolyester",
      //   "Category2_Unique": "TM>TM_Workwear>TM_Workwear_Knits",
      //   "Category2_Name": "Tri-Mountain>Workwear>Knits",
      //   "Category3_Unique": "TM>TM_Knits>TM_Knits_TMUltracool",
      //   "Category3_Name": "Tri-Mountain>Knits>Tri-Mountain Ultracool",
      //   "Category4_Unique": "TM>TM_Knits>TM_Knits_TMUltracool",
      //   "Category4_Name": "Tri-Mountain>Knits>Tri-Mountain Ultracool",
      //   "Category5_Unique": "ALL_HO>ALL_HO_Shirts",
      //   "Category5_Name": "Hospitality>Shirts",
      //   "Category6_Unique": "ALL_HO>ALL_HO_Shirts>ALL_HO_Shirts_Mens",
      //   "Category6_Name": "Hospitality>Shirts>Mens",
      //   "Product_Description": "<strong>Features:</strong><ul><li>Sentinel&&#35;45;Mens Cottonpoly 6040 Knit Polo Shirt W Mic Loops Pen Pocket</li></ul><a href='https://sellerscommerce.azureedge.net/images/147/size_chart_2013.pdf'target='_blank'>Click Here For Size Chart </a></li></ul></br>",
      //   "SKU_Description": "",
      //   "Large_Image_Path": "147/l/014_sentinel_bl.jpg",
      //   "Thumbnail_Image_Path": "147/s/014_sentinel_bl.jpg",
      //   "Supplier_Code": "",
      //   "Swatch_Image_Path": "147/sw/tm_black-bl_sw.jpg",
      //   "Color_Code": "Black-BL",
      //   "Color_Name": "Black (BL)",
      //   "Size_Code": "L",
      //   "Size_Name": "L",
      //   "Fit_Code": "Tall",
      //   "Fit_Name": "Tall"
      // },
      // {
      //   "Brand": "TM",
      //   "Manufacturer_ID": 14,
      //   "Product_Code": 14,
      //   "Product_Name": "Sentinel&#45;Mens Cottonpoly 6040 Knit Polo Shirt W Mic Loops Pen Pocket",
      //   "Supplier_SKU_ID": "014.BL.XLT",
      //   "Manufacturer_SKU_ID": "014.BL.XLT",
      //   "MSRP": 39,
      //   "MAP": 39,
      //   "Cost_Price": 39,
      //   "Weight": 1,
      //   "Stock": 1000,
      //   "SKU_Available_Date": "",
      //   "Category1_Unique": "TM>TM_Knits>TM_Knits_BlendedPolyester",
      //   "Category1_Name": "Tri-Mountain>Knits>BlendedPolyester",
      //   "Category2_Unique": "TM>TM_Workwear>TM_Workwear_Knits",
      //   "Category2_Name": "Tri-Mountain>Workwear>Knits",
      //   "Category3_Unique": "TM>TM_Knits>TM_Knits_TMUltracool",
      //   "Category3_Name": "Tri-Mountain>Knits>Tri-Mountain Ultracool",
      //   "Category4_Unique": "TM>TM_Knits>TM_Knits_TMUltracool",
      //   "Category4_Name": "Tri-Mountain>Knits>Tri-Mountain Ultracool",
      //   "Category5_Unique": "ALL_HO>ALL_HO_Shirts",
      //   "Category5_Name": "Hospitality>Shirts",
      //   "Category6_Unique": "ALL_HO>ALL_HO_Shirts>ALL_HO_Shirts_Mens",
      //   "Category6_Name": "Hospitality>Shirts>Mens",
      //   "Product_Description": "<strong>Features:</strong><ul><li>Sentinel&&#35;45;Mens Cottonpoly 6040 Knit Polo Shirt W Mic Loops Pen Pocket</li></ul><a href='https://sellerscommerce.azureedge.net/images/147/size_chart_2013.pdf'target='_blank'>Click Here For Size Chart </a></li></ul></br>",
      //   "SKU_Description": "",
      //   "Large_Image_Path": "147/l/014_sentinel_bl.jpg",
      //   "Thumbnail_Image_Path": "147/s/014_sentinel_bl.jpg",
      //   "Supplier_Code": "",
      //   "Swatch_Image_Path": "147/sw/tm_black-bl_sw.jpg",
      //   "Color_Code": "Black-BL",
      //   "Color_Name": "Black (BL)",
      //   "Size_Code": "XL",
      //   "Size_Name": "XL",
      //   "Fit_Code": "Tall",
      //   "Fit_Name": "Tall"
      // },
      // {
      //   "Brand": "TM",
      //   "Manufacturer_ID": 14,
      //   "Product_Code": 14,
      //   "Product_Name": "Sentinel&#45;Mens Cottonpoly 6040 Knit Polo Shirt W Mic Loops Pen Pocket",
      //   "Supplier_SKU_ID": "014.BL.2XLT",
      //   "Manufacturer_SKU_ID": "014.BL.2XLT",
      //   "MSRP": 41,
      //   "MAP": 41,
      //   "Cost_Price": 41,
      //   "Weight": 1,
      //   "Stock": 1000,
      //   "SKU_Available_Date": "",
      //   "Category1_Unique": "TM>TM_Knits>TM_Knits_BlendedPolyester",
      //   "Category1_Name": "Tri-Mountain>Knits>BlendedPolyester",
      //   "Category2_Unique": "TM>TM_Workwear>TM_Workwear_Knits",
      //   "Category2_Name": "Tri-Mountain>Workwear>Knits",
      //   "Category3_Unique": "TM>TM_Knits>TM_Knits_TMUltracool",
      //   "Category3_Name": "Tri-Mountain>Knits>Tri-Mountain Ultracool",
      //   "Category4_Unique": "TM>TM_Knits>TM_Knits_TMUltracool",
      //   "Category4_Name": "Tri-Mountain>Knits>Tri-Mountain Ultracool",
      //   "Category5_Unique": "ALL_HO>ALL_HO_Shirts",
      //   "Category5_Name": "Hospitality>Shirts",
      //   "Category6_Unique": "ALL_HO>ALL_HO_Shirts>ALL_HO_Shirts_Mens",
      //   "Category6_Name": "Hospitality>Shirts>Mens",
      //   "Product_Description": "<strong>Features:</strong><ul><li>Sentinel&&#35;45;Mens Cottonpoly 6040 Knit Polo Shirt W Mic Loops Pen Pocket</li></ul><a href='https://sellerscommerce.azureedge.net/images/147/size_chart_2013.pdf'target='_blank'>Click Here For Size Chart </a></li></ul></br>",
      //   "SKU_Description": "",
      //   "Large_Image_Path": "147/l/014_sentinel_bl.jpg",
      //   "Thumbnail_Image_Path": "147/s/014_sentinel_bl.jpg",
      //   "Supplier_Code": "",
      //   "Swatch_Image_Path": "147/sw/tm_black-bl_sw.jpg",
      //   "Color_Code": "Black-BL",
      //   "Color_Name": "Black (BL)",
      //   "Size_Code": "2XL",
      //   "Size_Name": "2XL",
      //   "Fit_Code": "Tall",
      //   "Fit_Name": "Tall"
      // },
      // {
      //   "Brand": "TM",
      //   "Manufacturer_ID": 14,
      //   "Product_Code": 14,
      //   "Product_Name": "Sentinel&#45;Mens Cottonpoly 6040 Knit Polo Shirt W Mic Loops Pen Pocket",
      //   "Supplier_SKU_ID": "014.BL.3XLT",
      //   "Manufacturer_SKU_ID": "014.BL.3XLT",
      //   "MSRP": 43,
      //   "MAP": 43,
      //   "Cost_Price": 43,
      //   "Weight": 1.11,
      //   "Stock": 1000,
      //   "SKU_Available_Date": "",
      //   "Category1_Unique": "TM>TM_Knits>TM_Knits_BlendedPolyester",
      //   "Category1_Name": "Tri-Mountain>Knits>BlendedPolyester",
      //   "Category2_Unique": "TM>TM_Workwear>TM_Workwear_Knits",
      //   "Category2_Name": "Tri-Mountain>Workwear>Knits",
      //   "Category3_Unique": "TM>TM_Knits>TM_Knits_TMUltracool",
      //   "Category3_Name": "Tri-Mountain>Knits>Tri-Mountain Ultracool",
      //   "Category4_Unique": "TM>TM_Knits>TM_Knits_TMUltracool",
      //   "Category4_Name": "Tri-Mountain>Knits>Tri-Mountain Ultracool",
      //   "Category5_Unique": "ALL_HO>ALL_HO_Shirts",
      //   "Category5_Name": "Hospitality>Shirts",
      //   "Category6_Unique": "ALL_HO>ALL_HO_Shirts>ALL_HO_Shirts_Mens",
      //   "Category6_Name": "Hospitality>Shirts>Mens",
      //   "Product_Description": "<strong>Features:</strong><ul><li>Sentinel&&#35;45;Mens Cottonpoly 6040 Knit Polo Shirt W Mic Loops Pen Pocket</li></ul><a href='https://sellerscommerce.azureedge.net/images/147/size_chart_2013.pdf'target='_blank'>Click Here For Size Chart </a></li></ul></br>",
      //   "SKU_Description": "",
      //   "Large_Image_Path": "147/l/014_sentinel_bl.jpg",
      //   "Thumbnail_Image_Path": "147/s/014_sentinel_bl.jpg",
      //   "Supplier_Code": "",
      //   "Swatch_Image_Path": "147/sw/tm_black-bl_sw.jpg",
      //   "Color_Code": "Black-BL",
      //   "Color_Name": "Black (BL)",
      //   "Size_Code": "3XL",
      //   "Size_Name": "3XL",
      //   "Fit_Code": "Tall",
      //   "Fit_Name": "Tall"
      // },
      // {
      //   "Brand": "TM",
      //   "Manufacturer_ID": 14,
      //   "Product_Code": 14,
      //   "Product_Name": "Sentinel&#45;Mens Cottonpoly 6040 Knit Polo Shirt W Mic Loops Pen Pocket",
      //   "Supplier_SKU_ID": "014.BL.4XLT",
      //   "Manufacturer_SKU_ID": "014.BL.4XLT",
      //   "MSRP": 45,
      //   "MAP": 45,
      //   "Cost_Price": 45,
      //   "Weight": 1.15,
      //   "Stock": 1000,
      //   "SKU_Available_Date": "",
      //   "Category1_Unique": "TM>TM_Knits>TM_Knits_BlendedPolyester",
      //   "Category1_Name": "Tri-Mountain>Knits>BlendedPolyester",
      //   "Category2_Unique": "TM>TM_Workwear>TM_Workwear_Knits",
      //   "Category2_Name": "Tri-Mountain>Workwear>Knits",
      //   "Category3_Unique": "TM>TM_Knits>TM_Knits_TMUltracool",
      //   "Category3_Name": "Tri-Mountain>Knits>Tri-Mountain Ultracool",
      //   "Category4_Unique": "TM>TM_Knits>TM_Knits_TMUltracool",
      //   "Category4_Name": "Tri-Mountain>Knits>Tri-Mountain Ultracool",
      //   "Category5_Unique": "ALL_HO>ALL_HO_Shirts",
      //   "Category5_Name": "Hospitality>Shirts",
      //   "Category6_Unique": "ALL_HO>ALL_HO_Shirts>ALL_HO_Shirts_Mens",
      //   "Category6_Name": "Hospitality>Shirts>Mens",
      //   "Product_Description": "<strong>Features:</strong><ul><li>Sentinel&&#35;45;Mens Cottonpoly 6040 Knit Polo Shirt W Mic Loops Pen Pocket</li></ul><a href='https://sellerscommerce.azureedge.net/images/147/size_chart_2013.pdf'target='_blank'>Click Here For Size Chart </a></li></ul></br>",
      //   "SKU_Description": "",
      //   "Large_Image_Path": "147/l/014_sentinel_bl.jpg",
      //   "Thumbnail_Image_Path": "147/s/014_sentinel_bl.jpg",
      //   "Supplier_Code": "",
      //   "Swatch_Image_Path": "147/sw/tm_black-bl_sw.jpg",
      //   "Color_Code": "Black-BL",
      //   "Color_Name": "Black (BL)",
      //   "Size_Code": "4XL",
      //   "Size_Name": "4XL",
      //   "Fit_Code": "Tall",
      //   "Fit_Name": "Tall"
      // },
      // {
      //   "Brand": "TM",
      //   "Manufacturer_ID": 14,
      //   "Product_Code": 14,
      //   "Product_Name": "Sentinel&#45;Mens Cottonpoly 6040 Knit Polo Shirt W Mic Loops Pen Pocket",
      //   "Supplier_SKU_ID": "014.CG.S",
      //   "Manufacturer_SKU_ID": "014.CG.S",
      //   "MSRP": 35,
      //   "MAP": 35,
      //   "Cost_Price": 35,
      //   "Weight": 1,
      //   "Stock": 1000,
      //   "SKU_Available_Date": "",
      //   "Category1_Unique": "TM>TM_Knits>TM_Knits_BlendedPolyester",
      //   "Category1_Name": "Tri-Mountain>Knits>BlendedPolyester",
      //   "Category2_Unique": "TM>TM_Workwear>TM_Workwear_Knits",
      //   "Category2_Name": "Tri-Mountain>Workwear>Knits",
      //   "Category3_Unique": "TM>TM_Knits>TM_Knits_TMUltracool",
      //   "Category3_Name": "Tri-Mountain>Knits>Tri-Mountain Ultracool",
      //   "Category4_Unique": "TM>TM_Knits>TM_Knits_TMUltracool",
      //   "Category4_Name": "Tri-Mountain>Knits>Tri-Mountain Ultracool",
      //   "Category5_Unique": "ALL_HO>ALL_HO_Shirts",
      //   "Category5_Name": "Hospitality>Shirts",
      //   "Category6_Unique": "ALL_HO>ALL_HO_Shirts>ALL_HO_Shirts_Mens",
      //   "Category6_Name": "Hospitality>Shirts>Mens",
      //   "Product_Description": "<strong>Features:</strong><ul><li>Sentinel&&#35;45;Mens Cottonpoly 6040 Knit Polo Shirt W Mic Loops Pen Pocket</li></ul><a href='https://sellerscommerce.azureedge.net/images/147/size_chart_2013.pdf'target='_blank'>Click Here For Size Chart </a></li></ul></br>",
      //   "SKU_Description": "",
      //   "Large_Image_Path": "147/l/014_sentinel_cg.jpg",
      //   "Thumbnail_Image_Path": "147/s/014_sentinel_cg.jpg",
      //   "Supplier_Code": "",
      //   "Swatch_Image_Path": "147/sw/tm_coolgray-cg_sw.jpg",
      //   "Color_Code": "CoolGray-CG",
      //   "Color_Name": "Cool Gray (CG)",
      //   "Size_Code": "S",
      //   "Size_Name": "S",
      //   "Fit_Code": "Regular",
      //   "Fit_Name": "Regular"
      // },
      // {
      //   "Brand": "TM",
      //   "Manufacturer_ID": 14,
      //   "Product_Code": 14,
      //   "Product_Name": "Sentinel&#45;Mens Cottonpoly 6040 Knit Polo Shirt W Mic Loops Pen Pocket",
      //   "Supplier_SKU_ID": "014.CG.M",
      //   "Manufacturer_SKU_ID": "014.CG.M",
      //   "MSRP": 35,
      //   "MAP": 35,
      //   "Cost_Price": 35,
      //   "Weight": 1,
      //   "Stock": 1000,
      //   "SKU_Available_Date": "",
      //   "Category1_Unique": "TM>TM_Knits>TM_Knits_BlendedPolyester",
      //   "Category1_Name": "Tri-Mountain>Knits>BlendedPolyester",
      //   "Category2_Unique": "TM>TM_Workwear>TM_Workwear_Knits",
      //   "Category2_Name": "Tri-Mountain>Workwear>Knits",
      //   "Category3_Unique": "TM>TM_Knits>TM_Knits_TMUltracool",
      //   "Category3_Name": "Tri-Mountain>Knits>Tri-Mountain Ultracool",
      //   "Category4_Unique": "TM>TM_Knits>TM_Knits_TMUltracool",
      //   "Category4_Name": "Tri-Mountain>Knits>Tri-Mountain Ultracool",
      //   "Category5_Unique": "ALL_HO>ALL_HO_Shirts",
      //   "Category5_Name": "Hospitality>Shirts",
      //   "Category6_Unique": "ALL_HO>ALL_HO_Shirts>ALL_HO_Shirts_Mens",
      //   "Category6_Name": "Hospitality>Shirts>Mens",
      //   "Product_Description": "<strong>Features:</strong><ul><li>Sentinel&&#35;45;Mens Cottonpoly 6040 Knit Polo Shirt W Mic Loops Pen Pocket</li></ul><a href='https://sellerscommerce.azureedge.net/images/147/size_chart_2013.pdf'target='_blank'>Click Here For Size Chart </a></li></ul></br>",
      //   "SKU_Description": "",
      //   "Large_Image_Path": "147/l/014_sentinel_cg.jpg",
      //   "Thumbnail_Image_Path": "147/s/014_sentinel_cg.jpg",
      //   "Supplier_Code": "",
      //   "Swatch_Image_Path": "147/sw/tm_coolgray-cg_sw.jpg",
      //   "Color_Code": "CoolGray-CG",
      //   "Color_Name": "Cool Gray (CG)",
      //   "Size_Code": "M",
      //   "Size_Name": "M",
      //   "Fit_Code": "Regular",
      //   "Fit_Name": "Regular"
      // },
      // {
      //   "Brand": "TM",
      //   "Manufacturer_ID": 14,
      //   "Product_Code": 14,
      //   "Product_Name": "Sentinel&#45;Mens Cottonpoly 6040 Knit Polo Shirt W Mic Loops Pen Pocket",
      //   "Supplier_SKU_ID": "014.CG.L",
      //   "Manufacturer_SKU_ID": "014.CG.L",
      //   "MSRP": 35,
      //   "MAP": 35,
      //   "Cost_Price": 35,
      //   "Weight": 1,
      //   "Stock": 1000,
      //   "SKU_Available_Date": "",
      //   "Category1_Unique": "TM>TM_Knits>TM_Knits_BlendedPolyester",
      //   "Category1_Name": "Tri-Mountain>Knits>BlendedPolyester",
      //   "Category2_Unique": "TM>TM_Workwear>TM_Workwear_Knits",
      //   "Category2_Name": "Tri-Mountain>Workwear>Knits",
      //   "Category3_Unique": "TM>TM_Knits>TM_Knits_TMUltracool",
      //   "Category3_Name": "Tri-Mountain>Knits>Tri-Mountain Ultracool",
      //   "Category4_Unique": "TM>TM_Knits>TM_Knits_TMUltracool",
      //   "Category4_Name": "Tri-Mountain>Knits>Tri-Mountain Ultracool",
      //   "Category5_Unique": "ALL_HO>ALL_HO_Shirts",
      //   "Category5_Name": "Hospitality>Shirts",
      //   "Category6_Unique": "ALL_HO>ALL_HO_Shirts>ALL_HO_Shirts_Mens",
      //   "Category6_Name": "Hospitality>Shirts>Mens",
      //   "Product_Description": "<strong>Features:</strong><ul><li>Sentinel&&#35;45;Mens Cottonpoly 6040 Knit Polo Shirt W Mic Loops Pen Pocket</li></ul><a href='https://sellerscommerce.azureedge.net/images/147/size_chart_2013.pdf'target='_blank'>Click Here For Size Chart </a></li></ul></br>",
      //   "SKU_Description": "",
      //   "Large_Image_Path": "147/l/014_sentinel_cg.jpg",
      //   "Thumbnail_Image_Path": "147/s/014_sentinel_cg.jpg",
      //   "Supplier_Code": "",
      //   "Swatch_Image_Path": "147/sw/tm_coolgray-cg_sw.jpg",
      //   "Color_Code": "CoolGray-CG",
      //   "Color_Name": "Cool Gray (CG)",
      //   "Size_Code": "L",
      //   "Size_Name": "L",
      //   "Fit_Code": "Regular",
      //   "Fit_Name": "Regular"
      // },
      // {
      //   "Brand": "TM",
      //   "Manufacturer_ID": 14,
      //   "Product_Code": 14,
      //   "Product_Name": "Sentinel&#45;Mens Cottonpoly 6040 Knit Polo Shirt W Mic Loops Pen Pocket",
      //   "Supplier_SKU_ID": "014.CG.XL",
      //   "Manufacturer_SKU_ID": "014.CG.XL",
      //   "MSRP": 35,
      //   "MAP": 35,
      //   "Cost_Price": 35,
      //   "Weight": 1,
      //   "Stock": 1000,
      //   "SKU_Available_Date": "",
      //   "Category1_Unique": "TM>TM_Knits>TM_Knits_BlendedPolyester",
      //   "Category1_Name": "Tri-Mountain>Knits>BlendedPolyester",
      //   "Category2_Unique": "TM>TM_Workwear>TM_Workwear_Knits",
      //   "Category2_Name": "Tri-Mountain>Workwear>Knits",
      //   "Category3_Unique": "TM>TM_Knits>TM_Knits_TMUltracool",
      //   "Category3_Name": "Tri-Mountain>Knits>Tri-Mountain Ultracool",
      //   "Category4_Unique": "TM>TM_Knits>TM_Knits_TMUltracool",
      //   "Category4_Name": "Tri-Mountain>Knits>Tri-Mountain Ultracool",
      //   "Category5_Unique": "ALL_HO>ALL_HO_Shirts",
      //   "Category5_Name": "Hospitality>Shirts",
      //   "Category6_Unique": "ALL_HO>ALL_HO_Shirts>ALL_HO_Shirts_Mens",
      //   "Category6_Name": "Hospitality>Shirts>Mens",
      //   "Product_Description": "<strong>Features:</strong><ul><li>Sentinel&&#35;45;Mens Cottonpoly 6040 Knit Polo Shirt W Mic Loops Pen Pocket</li></ul><a href='https://sellerscommerce.azureedge.net/images/147/size_chart_2013.pdf'target='_blank'>Click Here For Size Chart </a></li></ul></br>",
      //   "SKU_Description": "",
      //   "Large_Image_Path": "147/l/014_sentinel_cg.jpg",
      //   "Thumbnail_Image_Path": "147/s/014_sentinel_cg.jpg",
      //   "Supplier_Code": "",
      //   "Swatch_Image_Path": "147/sw/tm_coolgray-cg_sw.jpg",
      //   "Color_Code": "CoolGray-CG",
      //   "Color_Name": "Cool Gray (CG)",
      //   "Size_Code": "XL",
      //   "Size_Name": "XL",
      //   "Fit_Code": "Regular",
      //   "Fit_Name": "Regular"
      // },
      // {
      //   "Brand": "TM",
      //   "Manufacturer_ID": 14,
      //   "Product_Code": 14,
      //   "Product_Name": "Sentinel&#45;Mens Cottonpoly 6040 Knit Polo Shirt W Mic Loops Pen Pocket",
      //   "Supplier_SKU_ID": "014.CG.2XL",
      //   "Manufacturer_SKU_ID": "014.CG.2XL",
      //   "MSRP": 37,
      //   "MAP": 37,
      //   "Cost_Price": 37,
      //   "Weight": 1,
      //   "Stock": 1000,
      //   "SKU_Available_Date": "",
      //   "Category1_Unique": "TM>TM_Knits>TM_Knits_BlendedPolyester",
      //   "Category1_Name": "Tri-Mountain>Knits>BlendedPolyester",
      //   "Category2_Unique": "TM>TM_Workwear>TM_Workwear_Knits",
      //   "Category2_Name": "Tri-Mountain>Workwear>Knits",
      //   "Category3_Unique": "TM>TM_Knits>TM_Knits_TMUltracool",
      //   "Category3_Name": "Tri-Mountain>Knits>Tri-Mountain Ultracool",
      //   "Category4_Unique": "TM>TM_Knits>TM_Knits_TMUltracool",
      //   "Category4_Name": "Tri-Mountain>Knits>Tri-Mountain Ultracool",
      //   "Category5_Unique": "ALL_HO>ALL_HO_Shirts",
      //   "Category5_Name": "Hospitality>Shirts",
      //   "Category6_Unique": "ALL_HO>ALL_HO_Shirts>ALL_HO_Shirts_Mens",
      //   "Category6_Name": "Hospitality>Shirts>Mens",
      //   "Product_Description": "<strong>Features:</strong><ul><li>Sentinel&&#35;45;Mens Cottonpoly 6040 Knit Polo Shirt W Mic Loops Pen Pocket</li></ul><a href='https://sellerscommerce.azureedge.net/images/147/size_chart_2013.pdf'target='_blank'>Click Here For Size Chart </a></li></ul></br>",
      //   "SKU_Description": "",
      //   "Large_Image_Path": "147/l/014_sentinel_cg.jpg",
      //   "Thumbnail_Image_Path": "147/s/014_sentinel_cg.jpg",
      //   "Supplier_Code": "",
      //   "Swatch_Image_Path": "147/sw/tm_coolgray-cg_sw.jpg",
      //   "Color_Code": "CoolGray-CG",
      //   "Color_Name": "Cool Gray (CG)",
      //   "Size_Code": "2XL",
      //   "Size_Name": "2XL",
      //   "Fit_Code": "Regular",
      //   "Fit_Name": "Regular"
      // },
      // {
      //   "Brand": "TM",
      //   "Manufacturer_ID": 14,
      //   "Product_Code": 14,
      //   "Product_Name": "Sentinel&#45;Mens Cottonpoly 6040 Knit Polo Shirt W Mic Loops Pen Pocket",
      //   "Supplier_SKU_ID": "014.CG.3XL",
      //   "Manufacturer_SKU_ID": "014.CG.3XL",
      //   "MSRP": 39,
      //   "MAP": 39,
      //   "Cost_Price": 39,
      //   "Weight": 1,
      //   "Stock": 1000,
      //   "SKU_Available_Date": "",
      //   "Category1_Unique": "TM>TM_Knits>TM_Knits_BlendedPolyester",
      //   "Category1_Name": "Tri-Mountain>Knits>BlendedPolyester",
      //   "Category2_Unique": "TM>TM_Workwear>TM_Workwear_Knits",
      //   "Category2_Name": "Tri-Mountain>Workwear>Knits",
      //   "Category3_Unique": "TM>TM_Knits>TM_Knits_TMUltracool",
      //   "Category3_Name": "Tri-Mountain>Knits>Tri-Mountain Ultracool",
      //   "Category4_Unique": "TM>TM_Knits>TM_Knits_TMUltracool",
      //   "Category4_Name": "Tri-Mountain>Knits>Tri-Mountain Ultracool",
      //   "Category5_Unique": "ALL_HO>ALL_HO_Shirts",
      //   "Category5_Name": "Hospitality>Shirts",
      //   "Category6_Unique": "ALL_HO>ALL_HO_Shirts>ALL_HO_Shirts_Mens",
      //   "Category6_Name": "Hospitality>Shirts>Mens",
      //   "Product_Description": "<strong>Features:</strong><ul><li>Sentinel&&#35;45;Mens Cottonpoly 6040 Knit Polo Shirt W Mic Loops Pen Pocket</li></ul><a href='https://sellerscommerce.azureedge.net/images/147/size_chart_2013.pdf'target='_blank'>Click Here For Size Chart </a></li></ul></br>",
      //   "SKU_Description": "",
      //   "Large_Image_Path": "147/l/014_sentinel_cg.jpg",
      //   "Thumbnail_Image_Path": "147/s/014_sentinel_cg.jpg",
      //   "Supplier_Code": "",
      //   "Swatch_Image_Path": "147/sw/tm_coolgray-cg_sw.jpg",
      //   "Color_Code": "CoolGray-CG",
      //   "Color_Name": "Cool Gray (CG)",
      //   "Size_Code": "3XL",
      //   "Size_Name": "3XL",
      //   "Fit_Code": "Regular",
      //   "Fit_Name": "Regular"
      // },
      // {
      //   "Brand": "TM",
      //   "Manufacturer_ID": 14,
      //   "Product_Code": 14,
      //   "Product_Name": "Sentinel&#45;Mens Cottonpoly 6040 Knit Polo Shirt W Mic Loops Pen Pocket",
      //   "Supplier_SKU_ID": "014.CG.4XL",
      //   "Manufacturer_SKU_ID": "014.CG.4XL",
      //   "MSRP": 41,
      //   "MAP": 41,
      //   "Cost_Price": 41,
      //   "Weight": 1,
      //   "Stock": 1000,
      //   "SKU_Available_Date": "",
      //   "Category1_Unique": "TM>TM_Knits>TM_Knits_BlendedPolyester",
      //   "Category1_Name": "Tri-Mountain>Knits>BlendedPolyester",
      //   "Category2_Unique": "TM>TM_Workwear>TM_Workwear_Knits",
      //   "Category2_Name": "Tri-Mountain>Workwear>Knits",
      //   "Category3_Unique": "TM>TM_Knits>TM_Knits_TMUltracool",
      //   "Category3_Name": "Tri-Mountain>Knits>Tri-Mountain Ultracool",
      //   "Category4_Unique": "TM>TM_Knits>TM_Knits_TMUltracool",
      //   "Category4_Name": "Tri-Mountain>Knits>Tri-Mountain Ultracool",
      //   "Category5_Unique": "ALL_HO>ALL_HO_Shirts",
      //   "Category5_Name": "Hospitality>Shirts",
      //   "Category6_Unique": "ALL_HO>ALL_HO_Shirts>ALL_HO_Shirts_Mens",
      //   "Category6_Name": "Hospitality>Shirts>Mens",
      //   "Product_Description": "<strong>Features:</strong><ul><li>Sentinel&&#35;45;Mens Cottonpoly 6040 Knit Polo Shirt W Mic Loops Pen Pocket</li></ul><a href='https://sellerscommerce.azureedge.net/images/147/size_chart_2013.pdf'target='_blank'>Click Here For Size Chart </a></li></ul></br>",
      //   "SKU_Description": "",
      //   "Large_Image_Path": "147/l/014_sentinel_cg.jpg",
      //   "Thumbnail_Image_Path": "147/s/014_sentinel_cg.jpg",
      //   "Supplier_Code": "",
      //   "Swatch_Image_Path": "147/sw/tm_coolgray-cg_sw.jpg",
      //   "Color_Code": "CoolGray-CG",
      //   "Color_Name": "Cool Gray (CG)",
      //   "Size_Code": "4XL",
      //   "Size_Name": "4XL",
      //   "Fit_Code": "Regular",
      //   "Fit_Name": "Regular"
      // },
      // {
      //   "Brand": "TM",
      //   "Manufacturer_ID": 14,
      //   "Product_Code": 14,
      //   "Product_Name": "Sentinel&#45;Mens Cottonpoly 6040 Knit Polo Shirt W Mic Loops Pen Pocket",
      //   "Supplier_SKU_ID": "014.NA.S",
      //   "Manufacturer_SKU_ID": "014.NA.S",
      //   "MSRP": 35,
      //   "MAP": 35,
      //   "Cost_Price": 35,
      //   "Weight": 1,
      //   "Stock": 1000,
      //   "SKU_Available_Date": "",
      //   "Category1_Unique": "TM>TM_Knits>TM_Knits_BlendedPolyester",
      //   "Category1_Name": "Tri-Mountain>Knits>BlendedPolyester",
      //   "Category2_Unique": "TM>TM_Workwear>TM_Workwear_Knits",
      //   "Category2_Name": "Tri-Mountain>Workwear>Knits",
      //   "Category3_Unique": "TM>TM_Knits>TM_Knits_TMUltracool",
      //   "Category3_Name": "Tri-Mountain>Knits>Tri-Mountain Ultracool",
      //   "Category4_Unique": "TM>TM_Knits>TM_Knits_TMUltracool",
      //   "Category4_Name": "Tri-Mountain>Knits>Tri-Mountain Ultracool",
      //   "Category5_Unique": "ALL_HO>ALL_HO_Shirts",
      //   "Category5_Name": "Hospitality>Shirts",
      //   "Category6_Unique": "ALL_HO>ALL_HO_Shirts>ALL_HO_Shirts_Mens",
      //   "Category6_Name": "Hospitality>Shirts>Mens",
      //   "Product_Description": "<strong>Features:</strong><ul><li>Sentinel&&#35;45;Mens Cottonpoly 6040 Knit Polo Shirt W Mic Loops Pen Pocket</li></ul><a href='https://sellerscommerce.azureedge.net/images/147/size_chart_2013.pdf'target='_blank'>Click Here For Size Chart </a></li></ul></br>",
      //   "SKU_Description": "",
      //   "Large_Image_Path": "147/l/014_sentinel_na.jpg",
      //   "Thumbnail_Image_Path": "147/s/014_sentinel_na.jpg",
      //   "Supplier_Code": "",
      //   "Swatch_Image_Path": "147/sw/tm_navy-na_sw.jpg",
      //   "Color_Code": "Navy-NA",
      //   "Color_Name": "Navy (NA)",
      //   "Size_Code": "S",
      //   "Size_Name": "S",
      //   "Fit_Code": "Regular",
      //   "Fit_Name": "Regular"
      // },
      // {
      //   "Brand": "TM",
      //   "Manufacturer_ID": 14,
      //   "Product_Code": 14,
      //   "Product_Name": "Sentinel&#45;Mens Cottonpoly 6040 Knit Polo Shirt W Mic Loops Pen Pocket",
      //   "Supplier_SKU_ID": "014.NA.M",
      //   "Manufacturer_SKU_ID": "014.NA.M",
      //   "MSRP": 35,
      //   "MAP": 35,
      //   "Cost_Price": 35,
      //   "Weight": 1,
      //   "Stock": 1000,
      //   "SKU_Available_Date": "",
      //   "Category1_Unique": "TM>TM_Knits>TM_Knits_BlendedPolyester",
      //   "Category1_Name": "Tri-Mountain>Knits>BlendedPolyester",
      //   "Category2_Unique": "TM>TM_Workwear>TM_Workwear_Knits",
      //   "Category2_Name": "Tri-Mountain>Workwear>Knits",
      //   "Category3_Unique": "TM>TM_Knits>TM_Knits_TMUltracool",
      //   "Category3_Name": "Tri-Mountain>Knits>Tri-Mountain Ultracool",
      //   "Category4_Unique": "TM>TM_Knits>TM_Knits_TMUltracool",
      //   "Category4_Name": "Tri-Mountain>Knits>Tri-Mountain Ultracool",
      //   "Category5_Unique": "ALL_HO>ALL_HO_Shirts",
      //   "Category5_Name": "Hospitality>Shirts",
      //   "Category6_Unique": "ALL_HO>ALL_HO_Shirts>ALL_HO_Shirts_Mens",
      //   "Category6_Name": "Hospitality>Shirts>Mens",
      //   "Product_Description": "<strong>Features:</strong><ul><li>Sentinel&&#35;45;Mens Cottonpoly 6040 Knit Polo Shirt W Mic Loops Pen Pocket</li></ul><a href='https://sellerscommerce.azureedge.net/images/147/size_chart_2013.pdf'target='_blank'>Click Here For Size Chart </a></li></ul></br>",
      //   "SKU_Description": "",
      //   "Large_Image_Path": "147/l/014_sentinel_na.jpg",
      //   "Thumbnail_Image_Path": "147/s/014_sentinel_na.jpg",
      //   "Supplier_Code": "",
      //   "Swatch_Image_Path": "147/sw/tm_navy-na_sw.jpg",
      //   "Color_Code": "Navy-NA",
      //   "Color_Name": "Navy (NA)",
      //   "Size_Code": "M",
      //   "Size_Name": "M",
      //   "Fit_Code": "Regular",
      //   "Fit_Name": "Regular"
      // },
      // {
      //   "Brand": "TM",
      //   "Manufacturer_ID": 14,
      //   "Product_Code": 14,
      //   "Product_Name": "Sentinel&#45;Mens Cottonpoly 6040 Knit Polo Shirt W Mic Loops Pen Pocket",
      //   "Supplier_SKU_ID": "014.NA.L",
      //   "Manufacturer_SKU_ID": "014.NA.L",
      //   "MSRP": 35,
      //   "MAP": 35,
      //   "Cost_Price": 35,
      //   "Weight": 1,
      //   "Stock": 1000,
      //   "SKU_Available_Date": "",
      //   "Category1_Unique": "TM>TM_Knits>TM_Knits_BlendedPolyester",
      //   "Category1_Name": "Tri-Mountain>Knits>BlendedPolyester",
      //   "Category2_Unique": "TM>TM_Workwear>TM_Workwear_Knits",
      //   "Category2_Name": "Tri-Mountain>Workwear>Knits",
      //   "Category3_Unique": "TM>TM_Knits>TM_Knits_TMUltracool",
      //   "Category3_Name": "Tri-Mountain>Knits>Tri-Mountain Ultracool",
      //   "Category4_Unique": "TM>TM_Knits>TM_Knits_TMUltracool",
      //   "Category4_Name": "Tri-Mountain>Knits>Tri-Mountain Ultracool",
      //   "Category5_Unique": "ALL_HO>ALL_HO_Shirts",
      //   "Category5_Name": "Hospitality>Shirts",
      //   "Category6_Unique": "ALL_HO>ALL_HO_Shirts>ALL_HO_Shirts_Mens",
      //   "Category6_Name": "Hospitality>Shirts>Mens",
      //   "Product_Description": "<strong>Features:</strong><ul><li>Sentinel&&#35;45;Mens Cottonpoly 6040 Knit Polo Shirt W Mic Loops Pen Pocket</li></ul><a href='https://sellerscommerce.azureedge.net/images/147/size_chart_2013.pdf'target='_blank'>Click Here For Size Chart </a></li></ul></br>",
      //   "SKU_Description": "",
      //   "Large_Image_Path": "147/l/014_sentinel_na.jpg",
      //   "Thumbnail_Image_Path": "147/s/014_sentinel_na.jpg",
      //   "Supplier_Code": "",
      //   "Swatch_Image_Path": "147/sw/tm_navy-na_sw.jpg",
      //   "Color_Code": "Navy-NA",
      //   "Color_Name": "Navy (NA)",
      //   "Size_Code": "L",
      //   "Size_Name": "L",
      //   "Fit_Code": "Regular",
      //   "Fit_Name": "Regular"
      // },
      // {
      //   "Brand": "TM",
      //   "Manufacturer_ID": 14,
      //   "Product_Code": 14,
      //   "Product_Name": "Sentinel&#45;Mens Cottonpoly 6040 Knit Polo Shirt W Mic Loops Pen Pocket",
      //   "Supplier_SKU_ID": "014.NA.XL",
      //   "Manufacturer_SKU_ID": "014.NA.XL",
      //   "MSRP": 35,
      //   "MAP": 35,
      //   "Cost_Price": 35,
      //   "Weight": 1,
      //   "Stock": 1000,
      //   "SKU_Available_Date": "",
      //   "Category1_Unique": "TM>TM_Knits>TM_Knits_BlendedPolyester",
      //   "Category1_Name": "Tri-Mountain>Knits>BlendedPolyester",
      //   "Category2_Unique": "TM>TM_Workwear>TM_Workwear_Knits",
      //   "Category2_Name": "Tri-Mountain>Workwear>Knits",
      //   "Category3_Unique": "TM>TM_Knits>TM_Knits_TMUltracool",
      //   "Category3_Name": "Tri-Mountain>Knits>Tri-Mountain Ultracool",
      //   "Category4_Unique": "TM>TM_Knits>TM_Knits_TMUltracool",
      //   "Category4_Name": "Tri-Mountain>Knits>Tri-Mountain Ultracool",
      //   "Category5_Unique": "ALL_HO>ALL_HO_Shirts",
      //   "Category5_Name": "Hospitality>Shirts",
      //   "Category6_Unique": "ALL_HO>ALL_HO_Shirts>ALL_HO_Shirts_Mens",
      //   "Category6_Name": "Hospitality>Shirts>Mens",
      //   "Product_Description": "<strong>Features:</strong><ul><li>Sentinel&&#35;45;Mens Cottonpoly 6040 Knit Polo Shirt W Mic Loops Pen Pocket</li></ul><a href='https://sellerscommerce.azureedge.net/images/147/size_chart_2013.pdf'target='_blank'>Click Here For Size Chart </a></li></ul></br>",
      //   "SKU_Description": "",
      //   "Large_Image_Path": "147/l/014_sentinel_na.jpg",
      //   "Thumbnail_Image_Path": "147/s/014_sentinel_na.jpg",
      //   "Supplier_Code": "",
      //   "Swatch_Image_Path": "147/sw/tm_navy-na_sw.jpg",
      //   "Color_Code": "Navy-NA",
      //   "Color_Name": "Navy (NA)",
      //   "Size_Code": "XL",
      //   "Size_Name": "XL",
      //   "Fit_Code": "Regular",
      //   "Fit_Name": "Regular"
      // },
      // {
      //   "Brand": "TM",
      //   "Manufacturer_ID": 14,
      //   "Product_Code": 14,
      //   "Product_Name": "Sentinel&#45;Mens Cottonpoly 6040 Knit Polo Shirt W Mic Loops Pen Pocket",
      //   "Supplier_SKU_ID": "014.NA.2XL",
      //   "Manufacturer_SKU_ID": "014.NA.2XL",
      //   "MSRP": 37,
      //   "MAP": 37,
      //   "Cost_Price": 37,
      //   "Weight": 1,
      //   "Stock": 1000,
      //   "SKU_Available_Date": "",
      //   "Category1_Unique": "TM>TM_Knits>TM_Knits_BlendedPolyester",
      //   "Category1_Name": "Tri-Mountain>Knits>BlendedPolyester",
      //   "Category2_Unique": "TM>TM_Workwear>TM_Workwear_Knits",
      //   "Category2_Name": "Tri-Mountain>Workwear>Knits",
      //   "Category3_Unique": "TM>TM_Knits>TM_Knits_TMUltracool",
      //   "Category3_Name": "Tri-Mountain>Knits>Tri-Mountain Ultracool",
      //   "Category4_Unique": "TM>TM_Knits>TM_Knits_TMUltracool",
      //   "Category4_Name": "Tri-Mountain>Knits>Tri-Mountain Ultracool",
      //   "Category5_Unique": "ALL_HO>ALL_HO_Shirts",
      //   "Category5_Name": "Hospitality>Shirts",
      //   "Category6_Unique": "ALL_HO>ALL_HO_Shirts>ALL_HO_Shirts_Mens",
      //   "Category6_Name": "Hospitality>Shirts>Mens",
      //   "Product_Description": "<strong>Features:</strong><ul><li>Sentinel&&#35;45;Mens Cottonpoly 6040 Knit Polo Shirt W Mic Loops Pen Pocket</li></ul><a href='https://sellerscommerce.azureedge.net/images/147/size_chart_2013.pdf'target='_blank'>Click Here For Size Chart </a></li></ul></br>",
      //   "SKU_Description": "",
      //   "Large_Image_Path": "147/l/014_sentinel_na.jpg",
      //   "Thumbnail_Image_Path": "147/s/014_sentinel_na.jpg",
      //   "Supplier_Code": "",
      //   "Swatch_Image_Path": "147/sw/tm_navy-na_sw.jpg",
      //   "Color_Code": "Navy-NA",
      //   "Color_Name": "Navy (NA)",
      //   "Size_Code": "2XL",
      //   "Size_Name": "2XL",
      //   "Fit_Code": "Regular",
      //   "Fit_Name": "Regular"
      // },
      // {
      //   "Brand": "TM",
      //   "Manufacturer_ID": 14,
      //   "Product_Code": 14,
      //   "Product_Name": "Sentinel&#45;Mens Cottonpoly 6040 Knit Polo Shirt W Mic Loops Pen Pocket",
      //   "Supplier_SKU_ID": "014.NA.3XL",
      //   "Manufacturer_SKU_ID": "014.NA.3XL",
      //   "MSRP": 39,
      //   "MAP": 39,
      //   "Cost_Price": 39,
      //   "Weight": 1,
      //   "Stock": 1000,
      //   "SKU_Available_Date": "",
      //   "Category1_Unique": "TM>TM_Knits>TM_Knits_BlendedPolyester",
      //   "Category1_Name": "Tri-Mountain>Knits>BlendedPolyester",
      //   "Category2_Unique": "TM>TM_Workwear>TM_Workwear_Knits",
      //   "Category2_Name": "Tri-Mountain>Workwear>Knits",
      //   "Category3_Unique": "TM>TM_Knits>TM_Knits_TMUltracool",
      //   "Category3_Name": "Tri-Mountain>Knits>Tri-Mountain Ultracool",
      //   "Category4_Unique": "TM>TM_Knits>TM_Knits_TMUltracool",
      //   "Category4_Name": "Tri-Mountain>Knits>Tri-Mountain Ultracool",
      //   "Category5_Unique": "ALL_HO>ALL_HO_Shirts",
      //   "Category5_Name": "Hospitality>Shirts",
      //   "Category6_Unique": "ALL_HO>ALL_HO_Shirts>ALL_HO_Shirts_Mens",
      //   "Category6_Name": "Hospitality>Shirts>Mens",
      //   "Product_Description": "<strong>Features:</strong><ul><li>Sentinel&&#35;45;Mens Cottonpoly 6040 Knit Polo Shirt W Mic Loops Pen Pocket</li></ul><a href='https://sellerscommerce.azureedge.net/images/147/size_chart_2013.pdf'target='_blank'>Click Here For Size Chart </a></li></ul></br>",
      //   "SKU_Description": "",
      //   "Large_Image_Path": "147/l/014_sentinel_na.jpg",
      //   "Thumbnail_Image_Path": "147/s/014_sentinel_na.jpg",
      //   "Supplier_Code": "",
      //   "Swatch_Image_Path": "147/sw/tm_navy-na_sw.jpg",
      //   "Color_Code": "Navy-NA",
      //   "Color_Name": "Navy (NA)",
      //   "Size_Code": "3XL",
      //   "Size_Name": "3XL",
      //   "Fit_Code": "Regular",
      //   "Fit_Name": "Regular"
      // },
      // {
      //   "Brand": "TM",
      //   "Manufacturer_ID": 14,
      //   "Product_Code": 14,
      //   "Product_Name": "Sentinel&#45;Mens Cottonpoly 6040 Knit Polo Shirt W Mic Loops Pen Pocket",
      //   "Supplier_SKU_ID": "014.NA.4XL",
      //   "Manufacturer_SKU_ID": "014.NA.4XL",
      //   "MSRP": 41,
      //   "MAP": 41,
      //   "Cost_Price": 41,
      //   "Weight": 1,
      //   "Stock": 1000,
      //   "SKU_Available_Date": "",
      //   "Category1_Unique": "TM>TM_Knits>TM_Knits_BlendedPolyester",
      //   "Category1_Name": "Tri-Mountain>Knits>BlendedPolyester",
      //   "Category2_Unique": "TM>TM_Workwear>TM_Workwear_Knits",
      //   "Category2_Name": "Tri-Mountain>Workwear>Knits",
      //   "Category3_Unique": "TM>TM_Knits>TM_Knits_TMUltracool",
      //   "Category3_Name": "Tri-Mountain>Knits>Tri-Mountain Ultracool",
      //   "Category4_Unique": "TM>TM_Knits>TM_Knits_TMUltracool",
      //   "Category4_Name": "Tri-Mountain>Knits>Tri-Mountain Ultracool",
      //   "Category5_Unique": "ALL_HO>ALL_HO_Shirts",
      //   "Category5_Name": "Hospitality>Shirts",
      //   "Category6_Unique": "ALL_HO>ALL_HO_Shirts>ALL_HO_Shirts_Mens",
      //   "Category6_Name": "Hospitality>Shirts>Mens",
      //   "Product_Description": "<strong>Features:</strong><ul><li>Sentinel&&#35;45;Mens Cottonpoly 6040 Knit Polo Shirt W Mic Loops Pen Pocket</li></ul><a href='https://sellerscommerce.azureedge.net/images/147/size_chart_2013.pdf'target='_blank'>Click Here For Size Chart </a></li></ul></br>",
      //   "SKU_Description": "",
      //   "Large_Image_Path": "147/l/014_sentinel_na.jpg",
      //   "Thumbnail_Image_Path": "147/s/014_sentinel_na.jpg",
      //   "Supplier_Code": "",
      //   "Swatch_Image_Path": "147/sw/tm_navy-na_sw.jpg",
      //   "Color_Code": "Navy-NA",
      //   "Color_Name": "Navy (NA)",
      //   "Size_Code": "4XL",
      //   "Size_Name": "4XL",
      //   "Fit_Code": "Regular",
      //   "Fit_Name": "Regular"
      // },
      // {
      //   "Brand": "TM",
      //   "Manufacturer_ID": 14,
      //   "Product_Code": 14,
      //   "Product_Name": "Sentinel&#45;Mens Cottonpoly 6040 Knit Polo Shirt W Mic Loops Pen Pocket",
      //   "Supplier_SKU_ID": "014.NA.LT",
      //   "Manufacturer_SKU_ID": "014.NA.LT",
      //   "MSRP": 37,
      //   "MAP": 37,
      //   "Cost_Price": 37,
      //   "Weight": 1,
      //   "Stock": 1000,
      //   "SKU_Available_Date": "",
      //   "Category1_Unique": "TM>TM_Knits>TM_Knits_BlendedPolyester",
      //   "Category1_Name": "Tri-Mountain>Knits>BlendedPolyester",
      //   "Category2_Unique": "TM>TM_Workwear>TM_Workwear_Knits",
      //   "Category2_Name": "Tri-Mountain>Workwear>Knits",
      //   "Category3_Unique": "TM>TM_Knits>TM_Knits_TMUltracool",
      //   "Category3_Name": "Tri-Mountain>Knits>Tri-Mountain Ultracool",
      //   "Category4_Unique": "TM>TM_Knits>TM_Knits_TMUltracool",
      //   "Category4_Name": "Tri-Mountain>Knits>Tri-Mountain Ultracool",
      //   "Category5_Unique": "ALL_HO>ALL_HO_Shirts",
      //   "Category5_Name": "Hospitality>Shirts",
      //   "Category6_Unique": "ALL_HO>ALL_HO_Shirts>ALL_HO_Shirts_Mens",
      //   "Category6_Name": "Hospitality>Shirts>Mens",
      //   "Product_Description": "<strong>Features:</strong><ul><li>Sentinel&&#35;45;Mens Cottonpoly 6040 Knit Polo Shirt W Mic Loops Pen Pocket</li></ul><a href='https://sellerscommerce.azureedge.net/images/147/size_chart_2013.pdf'target='_blank'>Click Here For Size Chart </a></li></ul></br>",
      //   "SKU_Description": "",
      //   "Large_Image_Path": "147/l/014_sentinel_na.jpg",
      //   "Thumbnail_Image_Path": "147/s/014_sentinel_na.jpg",
      //   "Supplier_Code": "",
      //   "Swatch_Image_Path": "147/sw/tm_navy-na_sw.jpg",
      //   "Color_Code": "Navy-NA",
      //   "Color_Name": "Navy (NA)",
      //   "Size_Code": "L",
      //   "Size_Name": "L",
      //   "Fit_Code": "Tall",
      //   "Fit_Name": "Tall"
      // },
      // {
      //   "Brand": "TM",
      //   "Manufacturer_ID": 14,
      //   "Product_Code": 14,
      //   "Product_Name": "Sentinel&#45;Mens Cottonpoly 6040 Knit Polo Shirt W Mic Loops Pen Pocket",
      //   "Supplier_SKU_ID": "014.NA.XLT",
      //   "Manufacturer_SKU_ID": "014.NA.XLT",
      //   "MSRP": 39,
      //   "MAP": 39,
      //   "Cost_Price": 39,
      //   "Weight": 1,
      //   "Stock": 1000,
      //   "SKU_Available_Date": "",
      //   "Category1_Unique": "TM>TM_Knits>TM_Knits_BlendedPolyester",
      //   "Category1_Name": "Tri-Mountain>Knits>BlendedPolyester",
      //   "Category2_Unique": "TM>TM_Workwear>TM_Workwear_Knits",
      //   "Category2_Name": "Tri-Mountain>Workwear>Knits",
      //   "Category3_Unique": "TM>TM_Knits>TM_Knits_TMUltracool",
      //   "Category3_Name": "Tri-Mountain>Knits>Tri-Mountain Ultracool",
      //   "Category4_Unique": "TM>TM_Knits>TM_Knits_TMUltracool",
      //   "Category4_Name": "Tri-Mountain>Knits>Tri-Mountain Ultracool",
      //   "Category5_Unique": "ALL_HO>ALL_HO_Shirts",
      //   "Category5_Name": "Hospitality>Shirts",
      //   "Category6_Unique": "ALL_HO>ALL_HO_Shirts>ALL_HO_Shirts_Mens",
      //   "Category6_Name": "Hospitality>Shirts>Mens",
      //   "Product_Description": "<strong>Features:</strong><ul><li>Sentinel&&#35;45;Mens Cottonpoly 6040 Knit Polo Shirt W Mic Loops Pen Pocket</li></ul><a href='https://sellerscommerce.azureedge.net/images/147/size_chart_2013.pdf'target='_blank'>Click Here For Size Chart </a></li></ul></br>",
      //   "SKU_Description": "",
      //   "Large_Image_Path": "147/l/014_sentinel_na.jpg",
      //   "Thumbnail_Image_Path": "147/s/014_sentinel_na.jpg",
      //   "Supplier_Code": "",
      //   "Swatch_Image_Path": "147/sw/tm_navy-na_sw.jpg",
      //   "Color_Code": "Navy-NA",
      //   "Color_Name": "Navy (NA)",
      //   "Size_Code": "XL",
      //   "Size_Name": "XL",
      //   "Fit_Code": "Tall",
      //   "Fit_Name": "Tall"
      // },
      // {
      //   "Brand": "TM",
      //   "Manufacturer_ID": 14,
      //   "Product_Code": 14,
      //   "Product_Name": "Sentinel&#45;Mens Cottonpoly 6040 Knit Polo Shirt W Mic Loops Pen Pocket",
      //   "Supplier_SKU_ID": "014.NA.2XLT",
      //   "Manufacturer_SKU_ID": "014.NA.2XLT",
      //   "MSRP": 41,
      //   "MAP": 41,
      //   "Cost_Price": 41,
      //   "Weight": 1,
      //   "Stock": 1000,
      //   "SKU_Available_Date": "",
      //   "Category1_Unique": "TM>TM_Knits>TM_Knits_BlendedPolyester",
      //   "Category1_Name": "Tri-Mountain>Knits>BlendedPolyester",
      //   "Category2_Unique": "TM>TM_Workwear>TM_Workwear_Knits",
      //   "Category2_Name": "Tri-Mountain>Workwear>Knits",
      //   "Category3_Unique": "TM>TM_Knits>TM_Knits_TMUltracool",
      //   "Category3_Name": "Tri-Mountain>Knits>Tri-Mountain Ultracool",
      //   "Category4_Unique": "TM>TM_Knits>TM_Knits_TMUltracool",
      //   "Category4_Name": "Tri-Mountain>Knits>Tri-Mountain Ultracool",
      //   "Category5_Unique": "ALL_HO>ALL_HO_Shirts",
      //   "Category5_Name": "Hospitality>Shirts",
      //   "Category6_Unique": "ALL_HO>ALL_HO_Shirts>ALL_HO_Shirts_Mens",
      //   "Category6_Name": "Hospitality>Shirts>Mens",
      //   "Product_Description": "<strong>Features:</strong><ul><li>Sentinel&&#35;45;Mens Cottonpoly 6040 Knit Polo Shirt W Mic Loops Pen Pocket</li></ul><a href='https://sellerscommerce.azureedge.net/images/147/size_chart_2013.pdf'target='_blank'>Click Here For Size Chart </a></li></ul></br>",
      //   "SKU_Description": "",
      //   "Large_Image_Path": "147/l/014_sentinel_na.jpg",
      //   "Thumbnail_Image_Path": "147/s/014_sentinel_na.jpg",
      //   "Supplier_Code": "",
      //   "Swatch_Image_Path": "147/sw/tm_navy-na_sw.jpg",
      //   "Color_Code": "Navy-NA",
      //   "Color_Name": "Navy (NA)",
      //   "Size_Code": "2XL",
      //   "Size_Name": "2XL",
      //   "Fit_Code": "Tall",
      //   "Fit_Name": "Tall"
      // },
      // {
      //   "Brand": "TM",
      //   "Manufacturer_ID": 14,
      //   "Product_Code": 14,
      //   "Product_Name": "Sentinel&#45;Mens Cottonpoly 6040 Knit Polo Shirt W Mic Loops Pen Pocket",
      //   "Supplier_SKU_ID": "014.NA.3XLT",
      //   "Manufacturer_SKU_ID": "014.NA.3XLT",
      //   "MSRP": 43,
      //   "MAP": 43,
      //   "Cost_Price": 43,
      //   "Weight": 1.11,
      //   "Stock": 1000,
      //   "SKU_Available_Date": "",
      //   "Category1_Unique": "TM>TM_Knits>TM_Knits_BlendedPolyester",
      //   "Category1_Name": "Tri-Mountain>Knits>BlendedPolyester",
      //   "Category2_Unique": "TM>TM_Workwear>TM_Workwear_Knits",
      //   "Category2_Name": "Tri-Mountain>Workwear>Knits",
      //   "Category3_Unique": "TM>TM_Knits>TM_Knits_TMUltracool",
      //   "Category3_Name": "Tri-Mountain>Knits>Tri-Mountain Ultracool",
      //   "Category4_Unique": "TM>TM_Knits>TM_Knits_TMUltracool",
      //   "Category4_Name": "Tri-Mountain>Knits>Tri-Mountain Ultracool",
      //   "Category5_Unique": "ALL_HO>ALL_HO_Shirts",
      //   "Category5_Name": "Hospitality>Shirts",
      //   "Category6_Unique": "ALL_HO>ALL_HO_Shirts>ALL_HO_Shirts_Mens",
      //   "Category6_Name": "Hospitality>Shirts>Mens",
      //   "Product_Description": "<strong>Features:</strong><ul><li>Sentinel&&#35;45;Mens Cottonpoly 6040 Knit Polo Shirt W Mic Loops Pen Pocket</li></ul><a href='https://sellerscommerce.azureedge.net/images/147/size_chart_2013.pdf'target='_blank'>Click Here For Size Chart </a></li></ul></br>",
      //   "SKU_Description": "",
      //   "Large_Image_Path": "147/l/014_sentinel_na.jpg",
      //   "Thumbnail_Image_Path": "147/s/014_sentinel_na.jpg",
      //   "Supplier_Code": "",
      //   "Swatch_Image_Path": "147/sw/tm_navy-na_sw.jpg",
      //   "Color_Code": "Navy-NA",
      //   "Color_Name": "Navy (NA)",
      //   "Size_Code": "3XL",
      //   "Size_Name": "3XL",
      //   "Fit_Code": "Tall",
      //   "Fit_Name": "Tall"
      // },
      // {
      //   "Brand": "TM",
      //   "Manufacturer_ID": 14,
      //   "Product_Code": 14,
      //   "Product_Name": "Sentinel&#45;Mens Cottonpoly 6040 Knit Polo Shirt W Mic Loops Pen Pocket",
      //   "Supplier_SKU_ID": "014.NA.4XLT",
      //   "Manufacturer_SKU_ID": "014.NA.4XLT",
      //   "MSRP": 45,
      //   "MAP": 45,
      //   "Cost_Price": 45,
      //   "Weight": 1.15,
      //   "Stock": 1000,
      //   "SKU_Available_Date": "",
      //   "Category1_Unique": "TM>TM_Knits>TM_Knits_BlendedPolyester",
      //   "Category1_Name": "Tri-Mountain>Knits>BlendedPolyester",
      //   "Category2_Unique": "TM>TM_Workwear>TM_Workwear_Knits",
      //   "Category2_Name": "Tri-Mountain>Workwear>Knits",
      //   "Category3_Unique": "TM>TM_Knits>TM_Knits_TMUltracool",
      //   "Category3_Name": "Tri-Mountain>Knits>Tri-Mountain Ultracool",
      //   "Category4_Unique": "TM>TM_Knits>TM_Knits_TMUltracool",
      //   "Category4_Name": "Tri-Mountain>Knits>Tri-Mountain Ultracool",
      //   "Category5_Unique": "ALL_HO>ALL_HO_Shirts",
      //   "Category5_Name": "Hospitality>Shirts",
      //   "Category6_Unique": "ALL_HO>ALL_HO_Shirts>ALL_HO_Shirts_Mens",
      //   "Category6_Name": "Hospitality>Shirts>Mens",
      //   "Product_Description": "<strong>Features:</strong><ul><li>Sentinel&&#35;45;Mens Cottonpoly 6040 Knit Polo Shirt W Mic Loops Pen Pocket</li></ul><a href='https://sellerscommerce.azureedge.net/images/147/size_chart_2013.pdf'target='_blank'>Click Here For Size Chart </a></li></ul></br>",
      //   "SKU_Description": "",
      //   "Large_Image_Path": "147/l/014_sentinel_na.jpg",
      //   "Thumbnail_Image_Path": "147/s/014_sentinel_na.jpg",
      //   "Supplier_Code": "",
      //   "Swatch_Image_Path": "147/sw/tm_navy-na_sw.jpg",
      //   "Color_Code": "Navy-NA",
      //   "Color_Name": "Navy (NA)",
      //   "Size_Code": "4XL",
      //   "Size_Name": "4XL",
      //   "Fit_Code": "Tall",
      //   "Fit_Name": "Tall"
      // },
      // {
      //   "Brand": "TM",
      //   "Manufacturer_ID": 14,
      //   "Product_Code": 14,
      //   "Product_Name": "Sentinel&#45;Mens Cottonpoly 6040 Knit Polo Shirt W Mic Loops Pen Pocket",
      //   "Supplier_SKU_ID": "014.WH.S",
      //   "Manufacturer_SKU_ID": "014.WH.S",
      //   "MSRP": 35,
      //   "MAP": 35,
      //   "Cost_Price": 35,
      //   "Weight": 1,
      //   "Stock": 1000,
      //   "SKU_Available_Date": "",
      //   "Category1_Unique": "TM>TM_Knits>TM_Knits_BlendedPolyester",
      //   "Category1_Name": "Tri-Mountain>Knits>BlendedPolyester",
      //   "Category2_Unique": "TM>TM_Workwear>TM_Workwear_Knits",
      //   "Category2_Name": "Tri-Mountain>Workwear>Knits",
      //   "Category3_Unique": "TM>TM_Knits>TM_Knits_TMUltracool",
      //   "Category3_Name": "Tri-Mountain>Knits>Tri-Mountain Ultracool",
      //   "Category4_Unique": "TM>TM_Knits>TM_Knits_TMUltracool",
      //   "Category4_Name": "Tri-Mountain>Knits>Tri-Mountain Ultracool",
      //   "Category5_Unique": "ALL_HO>ALL_HO_Shirts",
      //   "Category5_Name": "Hospitality>Shirts",
      //   "Category6_Unique": "ALL_HO>ALL_HO_Shirts>ALL_HO_Shirts_Mens",
      //   "Category6_Name": "Hospitality>Shirts>Mens",
      //   "Product_Description": "<strong>Features:</strong><ul><li>Sentinel&&#35;45;Mens Cottonpoly 6040 Knit Polo Shirt W Mic Loops Pen Pocket</li></ul><a href='https://sellerscommerce.azureedge.net/images/147/size_chart_2013.pdf'target='_blank'>Click Here For Size Chart </a></li></ul></br>",
      //   "SKU_Description": "",
      //   "Large_Image_Path": "147/l/014_sentinel_wh.jpg",
      //   "Thumbnail_Image_Path": "147/s/014_sentinel_wh.jpg",
      //   "Supplier_Code": "",
      //   "Swatch_Image_Path": "147/sw/tm_white-wh_sw.jpg",
      //   "Color_Code": "White-WH",
      //   "Color_Name": "White (WH)",
      //   "Size_Code": "S",
      //   "Size_Name": "S",
      //   "Fit_Code": "Regular",
      //   "Fit_Name": "Regular"
      // },
      // {
      //   "Brand": "TM",
      //   "Manufacturer_ID": 14,
      //   "Product_Code": 14,
      //   "Product_Name": "Sentinel&#45;Mens Cottonpoly 6040 Knit Polo Shirt W Mic Loops Pen Pocket",
      //   "Supplier_SKU_ID": "014.WH.M",
      //   "Manufacturer_SKU_ID": "014.WH.M",
      //   "MSRP": 35,
      //   "MAP": 35,
      //   "Cost_Price": 35,
      //   "Weight": 1,
      //   "Stock": 1000,
      //   "SKU_Available_Date": "",
      //   "Category1_Unique": "TM>TM_Knits>TM_Knits_BlendedPolyester",
      //   "Category1_Name": "Tri-Mountain>Knits>BlendedPolyester",
      //   "Category2_Unique": "TM>TM_Workwear>TM_Workwear_Knits",
      //   "Category2_Name": "Tri-Mountain>Workwear>Knits",
      //   "Category3_Unique": "TM>TM_Knits>TM_Knits_TMUltracool",
      //   "Category3_Name": "Tri-Mountain>Knits>Tri-Mountain Ultracool",
      //   "Category4_Unique": "TM>TM_Knits>TM_Knits_TMUltracool",
      //   "Category4_Name": "Tri-Mountain>Knits>Tri-Mountain Ultracool",
      //   "Category5_Unique": "ALL_HO>ALL_HO_Shirts",
      //   "Category5_Name": "Hospitality>Shirts",
      //   "Category6_Unique": "ALL_HO>ALL_HO_Shirts>ALL_HO_Shirts_Mens",
      //   "Category6_Name": "Hospitality>Shirts>Mens",
      //   "Product_Description": "<strong>Features:</strong><ul><li>Sentinel&&#35;45;Mens Cottonpoly 6040 Knit Polo Shirt W Mic Loops Pen Pocket</li></ul><a href='https://sellerscommerce.azureedge.net/images/147/size_chart_2013.pdf'target='_blank'>Click Here For Size Chart </a></li></ul></br>",
      //   "SKU_Description": "",
      //   "Large_Image_Path": "147/l/014_sentinel_wh.jpg",
      //   "Thumbnail_Image_Path": "147/s/014_sentinel_wh.jpg",
      //   "Supplier_Code": "",
      //   "Swatch_Image_Path": "147/sw/tm_white-wh_sw.jpg",
      //   "Color_Code": "White-WH",
      //   "Color_Name": "White (WH)",
      //   "Size_Code": "M",
      //   "Size_Name": "M",
      //   "Fit_Code": "Regular",
      //   "Fit_Name": "Regular"
      // },
      // {
      //   "Brand": "TM",
      //   "Manufacturer_ID": 14,
      //   "Product_Code": 14,
      //   "Product_Name": "Sentinel&#45;Mens Cottonpoly 6040 Knit Polo Shirt W Mic Loops Pen Pocket",
      //   "Supplier_SKU_ID": "014.WH.L",
      //   "Manufacturer_SKU_ID": "014.WH.L",
      //   "MSRP": 35,
      //   "MAP": 35,
      //   "Cost_Price": 35,
      //   "Weight": 1,
      //   "Stock": 1000,
      //   "SKU_Available_Date": "",
      //   "Category1_Unique": "TM>TM_Knits>TM_Knits_BlendedPolyester",
      //   "Category1_Name": "Tri-Mountain>Knits>BlendedPolyester",
      //   "Category2_Unique": "TM>TM_Workwear>TM_Workwear_Knits",
      //   "Category2_Name": "Tri-Mountain>Workwear>Knits",
      //   "Category3_Unique": "TM>TM_Knits>TM_Knits_TMUltracool",
      //   "Category3_Name": "Tri-Mountain>Knits>Tri-Mountain Ultracool",
      //   "Category4_Unique": "TM>TM_Knits>TM_Knits_TMUltracool",
      //   "Category4_Name": "Tri-Mountain>Knits>Tri-Mountain Ultracool",
      //   "Category5_Unique": "ALL_HO>ALL_HO_Shirts",
      //   "Category5_Name": "Hospitality>Shirts",
      //   "Category6_Unique": "ALL_HO>ALL_HO_Shirts>ALL_HO_Shirts_Mens",
      //   "Category6_Name": "Hospitality>Shirts>Mens",
      //   "Product_Description": "<strong>Features:</strong><ul><li>Sentinel&&#35;45;Mens Cottonpoly 6040 Knit Polo Shirt W Mic Loops Pen Pocket</li></ul><a href='https://sellerscommerce.azureedge.net/images/147/size_chart_2013.pdf'target='_blank'>Click Here For Size Chart </a></li></ul></br>",
      //   "SKU_Description": "",
      //   "Large_Image_Path": "147/l/014_sentinel_wh.jpg",
      //   "Thumbnail_Image_Path": "147/s/014_sentinel_wh.jpg",
      //   "Supplier_Code": "",
      //   "Swatch_Image_Path": "147/sw/tm_white-wh_sw.jpg",
      //   "Color_Code": "White-WH",
      //   "Color_Name": "White (WH)",
      //   "Size_Code": "L",
      //   "Size_Name": "L",
      //   "Fit_Code": "Regular",
      //   "Fit_Name": "Regular"
      // },
      // {
      //   "Brand": "TM",
      //   "Manufacturer_ID": 14,
      //   "Product_Code": 14,
      //   "Product_Name": "Sentinel&#45;Mens Cottonpoly 6040 Knit Polo Shirt W Mic Loops Pen Pocket",
      //   "Supplier_SKU_ID": "014.WH.XL",
      //   "Manufacturer_SKU_ID": "014.WH.XL",
      //   "MSRP": 35,
      //   "MAP": 35,
      //   "Cost_Price": 35,
      //   "Weight": 1,
      //   "Stock": 1000,
      //   "SKU_Available_Date": "",
      //   "Category1_Unique": "TM>TM_Knits>TM_Knits_BlendedPolyester",
      //   "Category1_Name": "Tri-Mountain>Knits>BlendedPolyester",
      //   "Category2_Unique": "TM>TM_Workwear>TM_Workwear_Knits",
      //   "Category2_Name": "Tri-Mountain>Workwear>Knits",
      //   "Category3_Unique": "TM>TM_Knits>TM_Knits_TMUltracool",
      //   "Category3_Name": "Tri-Mountain>Knits>Tri-Mountain Ultracool",
      //   "Category4_Unique": "TM>TM_Knits>TM_Knits_TMUltracool",
      //   "Category4_Name": "Tri-Mountain>Knits>Tri-Mountain Ultracool",
      //   "Category5_Unique": "ALL_HO>ALL_HO_Shirts",
      //   "Category5_Name": "Hospitality>Shirts",
      //   "Category6_Unique": "ALL_HO>ALL_HO_Shirts>ALL_HO_Shirts_Mens",
      //   "Category6_Name": "Hospitality>Shirts>Mens",
      //   "Product_Description": "<strong>Features:</strong><ul><li>Sentinel&&#35;45;Mens Cottonpoly 6040 Knit Polo Shirt W Mic Loops Pen Pocket</li></ul><a href='https://sellerscommerce.azureedge.net/images/147/size_chart_2013.pdf'target='_blank'>Click Here For Size Chart </a></li></ul></br>",
      //   "SKU_Description": "",
      //   "Large_Image_Path": "147/l/014_sentinel_wh.jpg",
      //   "Thumbnail_Image_Path": "147/s/014_sentinel_wh.jpg",
      //   "Supplier_Code": "",
      //   "Swatch_Image_Path": "147/sw/tm_white-wh_sw.jpg",
      //   "Color_Code": "White-WH",
      //   "Color_Name": "White (WH)",
      //   "Size_Code": "XL",
      //   "Size_Name": "XL",
      //   "Fit_Code": "Regular",
      //   "Fit_Name": "Regular"
      // },
      // {
      //   "Brand": "TM",
      //   "Manufacturer_ID": 14,
      //   "Product_Code": 14,
      //   "Product_Name": "Sentinel&#45;Mens Cottonpoly 6040 Knit Polo Shirt W Mic Loops Pen Pocket",
      //   "Supplier_SKU_ID": "014.WH.2XL",
      //   "Manufacturer_SKU_ID": "014.WH.2XL",
      //   "MSRP": 37,
      //   "MAP": 37,
      //   "Cost_Price": 37,
      //   "Weight": 1,
      //   "Stock": 1000,
      //   "SKU_Available_Date": "",
      //   "Category1_Unique": "TM>TM_Knits>TM_Knits_BlendedPolyester",
      //   "Category1_Name": "Tri-Mountain>Knits>BlendedPolyester",
      //   "Category2_Unique": "TM>TM_Workwear>TM_Workwear_Knits",
      //   "Category2_Name": "Tri-Mountain>Workwear>Knits",
      //   "Category3_Unique": "TM>TM_Knits>TM_Knits_TMUltracool",
      //   "Category3_Name": "Tri-Mountain>Knits>Tri-Mountain Ultracool",
      //   "Category4_Unique": "TM>TM_Knits>TM_Knits_TMUltracool",
      //   "Category4_Name": "Tri-Mountain>Knits>Tri-Mountain Ultracool",
      //   "Category5_Unique": "ALL_HO>ALL_HO_Shirts",
      //   "Category5_Name": "Hospitality>Shirts",
      //   "Category6_Unique": "ALL_HO>ALL_HO_Shirts>ALL_HO_Shirts_Mens",
      //   "Category6_Name": "Hospitality>Shirts>Mens",
      //   "Product_Description": "<strong>Features:</strong><ul><li>Sentinel&&#35;45;Mens Cottonpoly 6040 Knit Polo Shirt W Mic Loops Pen Pocket</li></ul><a href='https://sellerscommerce.azureedge.net/images/147/size_chart_2013.pdf'target='_blank'>Click Here For Size Chart </a></li></ul></br>",
      //   "SKU_Description": "",
      //   "Large_Image_Path": "147/l/014_sentinel_wh.jpg",
      //   "Thumbnail_Image_Path": "147/s/014_sentinel_wh.jpg",
      //   "Supplier_Code": "",
      //   "Swatch_Image_Path": "147/sw/tm_white-wh_sw.jpg",
      //   "Color_Code": "White-WH",
      //   "Color_Name": "White (WH)",
      //   "Size_Code": "2XL",
      //   "Size_Name": "2XL",
      //   "Fit_Code": "Regular",
      //   "Fit_Name": "Regular"
      // },
      // {
      //   "Brand": "TM",
      //   "Manufacturer_ID": 14,
      //   "Product_Code": 14,
      //   "Product_Name": "Sentinel&#45;Mens Cottonpoly 6040 Knit Polo Shirt W Mic Loops Pen Pocket",
      //   "Supplier_SKU_ID": "014.WH.3XL",
      //   "Manufacturer_SKU_ID": "014.WH.3XL",
      //   "MSRP": 39,
      //   "MAP": 39,
      //   "Cost_Price": 39,
      //   "Weight": 1,
      //   "Stock": 1000,
      //   "SKU_Available_Date": "",
      //   "Category1_Unique": "TM>TM_Knits>TM_Knits_BlendedPolyester",
      //   "Category1_Name": "Tri-Mountain>Knits>BlendedPolyester",
      //   "Category2_Unique": "TM>TM_Workwear>TM_Workwear_Knits",
      //   "Category2_Name": "Tri-Mountain>Workwear>Knits",
      //   "Category3_Unique": "TM>TM_Knits>TM_Knits_TMUltracool",
      //   "Category3_Name": "Tri-Mountain>Knits>Tri-Mountain Ultracool",
      //   "Category4_Unique": "TM>TM_Knits>TM_Knits_TMUltracool",
      //   "Category4_Name": "Tri-Mountain>Knits>Tri-Mountain Ultracool",
      //   "Category5_Unique": "ALL_HO>ALL_HO_Shirts",
      //   "Category5_Name": "Hospitality>Shirts",
      //   "Category6_Unique": "ALL_HO>ALL_HO_Shirts>ALL_HO_Shirts_Mens",
      //   "Category6_Name": "Hospitality>Shirts>Mens",
      //   "Product_Description": "<strong>Features:</strong><ul><li>Sentinel&&#35;45;Mens Cottonpoly 6040 Knit Polo Shirt W Mic Loops Pen Pocket</li></ul><a href='https://sellerscommerce.azureedge.net/images/147/size_chart_2013.pdf'target='_blank'>Click Here For Size Chart </a></li></ul></br>",
      //   "SKU_Description": "",
      //   "Large_Image_Path": "147/l/014_sentinel_wh.jpg",
      //   "Thumbnail_Image_Path": "147/s/014_sentinel_wh.jpg",
      //   "Supplier_Code": "",
      //   "Swatch_Image_Path": "147/sw/tm_white-wh_sw.jpg",
      //   "Color_Code": "White-WH",
      //   "Color_Name": "White (WH)",
      //   "Size_Code": "3XL",
      //   "Size_Name": "3XL",
      //   "Fit_Code": "Regular",
      //   "Fit_Name": "Regular"
      // },
      // {
      //   "Brand": "TM",
      //   "Manufacturer_ID": 14,
      //   "Product_Code": 14,
      //   "Product_Name": "Sentinel&#45;Mens Cottonpoly 6040 Knit Polo Shirt W Mic Loops Pen Pocket",
      //   "Supplier_SKU_ID": "014.WH.4XL",
      //   "Manufacturer_SKU_ID": "014.WH.4XL",
      //   "MSRP": 41,
      //   "MAP": 41,
      //   "Cost_Price": 41,
      //   "Weight": 1,
      //   "Stock": 1000,
      //   "SKU_Available_Date": "",
      //   "Category1_Unique": "TM>TM_Knits>TM_Knits_BlendedPolyester",
      //   "Category1_Name": "Tri-Mountain>Knits>BlendedPolyester",
      //   "Category2_Unique": "TM>TM_Workwear>TM_Workwear_Knits",
      //   "Category2_Name": "Tri-Mountain>Workwear>Knits",
      //   "Category3_Unique": "TM>TM_Knits>TM_Knits_TMUltracool",
      //   "Category3_Name": "Tri-Mountain>Knits>Tri-Mountain Ultracool",
      //   "Category4_Unique": "TM>TM_Knits>TM_Knits_TMUltracool",
      //   "Category4_Name": "Tri-Mountain>Knits>Tri-Mountain Ultracool",
      //   "Category5_Unique": "ALL_HO>ALL_HO_Shirts",
      //   "Category5_Name": "Hospitality>Shirts",
      //   "Category6_Unique": "ALL_HO>ALL_HO_Shirts>ALL_HO_Shirts_Mens",
      //   "Category6_Name": "Hospitality>Shirts>Mens",
      //   "Product_Description": "<strong>Features:</strong><ul><li>Sentinel&&#35;45;Mens Cottonpoly 6040 Knit Polo Shirt W Mic Loops Pen Pocket</li></ul><a href='https://sellerscommerce.azureedge.net/images/147/size_chart_2013.pdf'target='_blank'>Click Here For Size Chart </a></li></ul></br>",
      //   "SKU_Description": "",
      //   "Large_Image_Path": "147/l/014_sentinel_wh.jpg",
      //   "Thumbnail_Image_Path": "147/s/014_sentinel_wh.jpg",
      //   "Supplier_Code": "",
      //   "Swatch_Image_Path": "147/sw/tm_white-wh_sw.jpg",
      //   "Color_Code": "White-WH",
      //   "Color_Name": "White (WH)",
      //   "Size_Code": "4XL",
      //   "Size_Name": "4XL",
      //   "Fit_Code": "Regular",
      //   "Fit_Name": "Regular"
      // }
    ]
  }
}
